/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.gello.grammar.node;

import org.gello.grammar.analysis.*;

@SuppressWarnings("nls")
public final class AIfLetExpression extends PLetExpression
{
    private PIfExpression _ifExpression_;

    public AIfLetExpression()
    {
        // Constructor
    }

    public AIfLetExpression(
        @SuppressWarnings("hiding") PIfExpression _ifExpression_)
    {
        // Constructor
        setIfExpression(_ifExpression_);

    }

    @Override
    public Object clone()
    {
        return new AIfLetExpression(
            cloneNode(this._ifExpression_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIfLetExpression(this);
    }

    public PIfExpression getIfExpression()
    {
        return this._ifExpression_;
    }

    public void setIfExpression(PIfExpression node)
    {
        if(this._ifExpression_ != null)
        {
            this._ifExpression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._ifExpression_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._ifExpression_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._ifExpression_ == child)
        {
            this._ifExpression_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._ifExpression_ == oldChild)
        {
            setIfExpression((PIfExpression) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
