/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.gello.grammar.node;

import org.gello.grammar.analysis.*;

@SuppressWarnings("nls")
public final class AGelloType extends PType
{
    private PGelloType _gelloType_;

    public AGelloType()
    {
        // Constructor
    }

    public AGelloType(
        @SuppressWarnings("hiding") PGelloType _gelloType_)
    {
        // Constructor
        setGelloType(_gelloType_);

    }

    @Override
    public Object clone()
    {
        return new AGelloType(
            cloneNode(this._gelloType_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAGelloType(this);
    }

    public PGelloType getGelloType()
    {
        return this._gelloType_;
    }

    public void setGelloType(PGelloType node)
    {
        if(this._gelloType_ != null)
        {
            this._gelloType_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._gelloType_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._gelloType_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._gelloType_ == child)
        {
            this._gelloType_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._gelloType_ == oldChild)
        {
            setGelloType((PGelloType) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
