/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.gello.grammar.node;

import org.gello.grammar.analysis.*;

@SuppressWarnings("nls")
public final class TBag extends Token
{
    public TBag()
    {
        super.setText("bag");
    }

    public TBag(int line, int pos)
    {
        super.setText("bag");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TBag(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTBag(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TBag text.");
    }
}
