/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.gello.grammar.node;

import org.gello.grammar.analysis.*;

@SuppressWarnings("nls")
public final class TIntdiv extends Token
{
    public TIntdiv()
    {
        super.setText("div");
    }

    public TIntdiv(int line, int pos)
    {
        super.setText("div");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TIntdiv(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTIntdiv(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TIntdiv text.");
    }
}
