/*******************************************************************************
 * Copyright (c) 2006, 2007 Pfizer, Inc.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *   Jacob Brauer (WebReach, Inc.) - initial implementation
 *******************************************************************************/


package org.gello.runtime;

import java.io.InputStream;
import java.io.OutputStream;

/**
 * IGelloModel is the interface that Gello Runtime and Compiler use to
 * communicate with concrete models, such as the HL7 model.
 * 
 * FUTURE:
 *  - How should the GELLO concept of "context" interact with the code
 *    generated by the compiler and the data model?
 * @author zubint
 * @author Erik Horstkotte
 */
public interface IGelloModel {

	/**
	 * Returns the root object in the selected context of the model.
	 */
	public Object getContextRoot();

	/**
	 * Returns the class of the root object in the selected context of the model.
	 * 
	 * @return The java Class of the root object in the selected context of the model.
	 */
	public Class getContextRootClass();

	/**
	 * Save the information in the model to an input stream
	 * 
	 * @param path
	 */
	public void saveData(OutputStream stream) throws GelloModelException;

	/**
	 * Parses an input stream for errors and returns a list of exceptions that occurred on compilation
	 * 
	 * @param path
	 */
	public CompileMessage[] parseData(InputStream stream) throws GelloModelException;

	/**
	 * Loads the model with information from an input stream
	 * 
	 * @param path
	 */
	public void loadData(InputStream stream) throws GelloModelException;

	/**
	 * Loads the model with default information
	 */
	public void loadDataDefault() throws GelloModelException;
}
