/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.gello.grammar.node;

import org.gello.grammar.analysis.*;

@SuppressWarnings("nls")
public final class ABasicGelloType extends PGelloType
{
    private PBasicType _basicType_;

    public ABasicGelloType()
    {
        // Constructor
    }

    public ABasicGelloType(
        @SuppressWarnings("hiding") PBasicType _basicType_)
    {
        // Constructor
        setBasicType(_basicType_);

    }

    @Override
    public Object clone()
    {
        return new ABasicGelloType(
            cloneNode(this._basicType_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABasicGelloType(this);
    }

    public PBasicType getBasicType()
    {
        return this._basicType_;
    }

    public void setBasicType(PBasicType node)
    {
        if(this._basicType_ != null)
        {
            this._basicType_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._basicType_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._basicType_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._basicType_ == child)
        {
            this._basicType_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._basicType_ == oldChild)
        {
            setBasicType((PBasicType) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
