/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.gello.grammar.node;

import org.gello.grammar.analysis.*;

@SuppressWarnings("nls")
public final class ABindingTupleLiteralList extends PTupleLiteralList
{
    private PTypedVarDefinition _typedVarDefinition_;

    public ABindingTupleLiteralList()
    {
        // Constructor
    }

    public ABindingTupleLiteralList(
        @SuppressWarnings("hiding") PTypedVarDefinition _typedVarDefinition_)
    {
        // Constructor
        setTypedVarDefinition(_typedVarDefinition_);

    }

    @Override
    public Object clone()
    {
        return new ABindingTupleLiteralList(
            cloneNode(this._typedVarDefinition_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABindingTupleLiteralList(this);
    }

    public PTypedVarDefinition getTypedVarDefinition()
    {
        return this._typedVarDefinition_;
    }

    public void setTypedVarDefinition(PTypedVarDefinition node)
    {
        if(this._typedVarDefinition_ != null)
        {
            this._typedVarDefinition_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._typedVarDefinition_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._typedVarDefinition_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._typedVarDefinition_ == child)
        {
            this._typedVarDefinition_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._typedVarDefinition_ == oldChild)
        {
            setTypedVarDefinition((PTypedVarDefinition) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
