/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.gello.grammar.node;

import org.gello.grammar.analysis.*;

@SuppressWarnings("nls")
public final class AContextGoal extends PGoal
{
    private PContextExpression _contextExpression_;

    public AContextGoal()
    {
        // Constructor
    }

    public AContextGoal(
        @SuppressWarnings("hiding") PContextExpression _contextExpression_)
    {
        // Constructor
        setContextExpression(_contextExpression_);

    }

    @Override
    public Object clone()
    {
        return new AContextGoal(
            cloneNode(this._contextExpression_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAContextGoal(this);
    }

    public PContextExpression getContextExpression()
    {
        return this._contextExpression_;
    }

    public void setContextExpression(PContextExpression node)
    {
        if(this._contextExpression_ != null)
        {
            this._contextExpression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._contextExpression_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._contextExpression_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._contextExpression_ == child)
        {
            this._contextExpression_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._contextExpression_ == oldChild)
        {
            setContextExpression((PContextExpression) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
