/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.gello.grammar.node;

import org.gello.grammar.analysis.*;

@SuppressWarnings("nls")
public final class AImpliesConditionalExpression extends PConditionalExpression
{
    private PConditionalExpression _conditionalExpression_;
    private TImplies _implies_;
    private PConditionalOrExpression _conditionalOrExpression_;

    public AImpliesConditionalExpression()
    {
        // Constructor
    }

    public AImpliesConditionalExpression(
        @SuppressWarnings("hiding") PConditionalExpression _conditionalExpression_,
        @SuppressWarnings("hiding") TImplies _implies_,
        @SuppressWarnings("hiding") PConditionalOrExpression _conditionalOrExpression_)
    {
        // Constructor
        setConditionalExpression(_conditionalExpression_);

        setImplies(_implies_);

        setConditionalOrExpression(_conditionalOrExpression_);

    }

    @Override
    public Object clone()
    {
        return new AImpliesConditionalExpression(
            cloneNode(this._conditionalExpression_),
            cloneNode(this._implies_),
            cloneNode(this._conditionalOrExpression_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAImpliesConditionalExpression(this);
    }

    public PConditionalExpression getConditionalExpression()
    {
        return this._conditionalExpression_;
    }

    public void setConditionalExpression(PConditionalExpression node)
    {
        if(this._conditionalExpression_ != null)
        {
            this._conditionalExpression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._conditionalExpression_ = node;
    }

    public TImplies getImplies()
    {
        return this._implies_;
    }

    public void setImplies(TImplies node)
    {
        if(this._implies_ != null)
        {
            this._implies_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._implies_ = node;
    }

    public PConditionalOrExpression getConditionalOrExpression()
    {
        return this._conditionalOrExpression_;
    }

    public void setConditionalOrExpression(PConditionalOrExpression node)
    {
        if(this._conditionalOrExpression_ != null)
        {
            this._conditionalOrExpression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._conditionalOrExpression_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._conditionalExpression_)
            + toString(this._implies_)
            + toString(this._conditionalOrExpression_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._conditionalExpression_ == child)
        {
            this._conditionalExpression_ = null;
            return;
        }

        if(this._implies_ == child)
        {
            this._implies_ = null;
            return;
        }

        if(this._conditionalOrExpression_ == child)
        {
            this._conditionalOrExpression_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._conditionalExpression_ == oldChild)
        {
            setConditionalExpression((PConditionalExpression) newChild);
            return;
        }

        if(this._implies_ == oldChild)
        {
            setImplies((TImplies) newChild);
            return;
        }

        if(this._conditionalOrExpression_ == oldChild)
        {
            setConditionalOrExpression((PConditionalOrExpression) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
