/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.gello.grammar.node;

import org.gello.grammar.analysis.*;

@SuppressWarnings("nls")
public final class ARangeCollectionLiteralArgument extends PCollectionLiteralArgument
{
    private TLBracket _lBracket_;
    private PExpression _begin_;
    private TDotdot _dotdot_;
    private PExpression _end_;
    private TRBracket _rBracket_;

    public ARangeCollectionLiteralArgument()
    {
        // Constructor
    }

    public ARangeCollectionLiteralArgument(
        @SuppressWarnings("hiding") TLBracket _lBracket_,
        @SuppressWarnings("hiding") PExpression _begin_,
        @SuppressWarnings("hiding") TDotdot _dotdot_,
        @SuppressWarnings("hiding") PExpression _end_,
        @SuppressWarnings("hiding") TRBracket _rBracket_)
    {
        // Constructor
        setLBracket(_lBracket_);

        setBegin(_begin_);

        setDotdot(_dotdot_);

        setEnd(_end_);

        setRBracket(_rBracket_);

    }

    @Override
    public Object clone()
    {
        return new ARangeCollectionLiteralArgument(
            cloneNode(this._lBracket_),
            cloneNode(this._begin_),
            cloneNode(this._dotdot_),
            cloneNode(this._end_),
            cloneNode(this._rBracket_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseARangeCollectionLiteralArgument(this);
    }

    public TLBracket getLBracket()
    {
        return this._lBracket_;
    }

    public void setLBracket(TLBracket node)
    {
        if(this._lBracket_ != null)
        {
            this._lBracket_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._lBracket_ = node;
    }

    public PExpression getBegin()
    {
        return this._begin_;
    }

    public void setBegin(PExpression node)
    {
        if(this._begin_ != null)
        {
            this._begin_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._begin_ = node;
    }

    public TDotdot getDotdot()
    {
        return this._dotdot_;
    }

    public void setDotdot(TDotdot node)
    {
        if(this._dotdot_ != null)
        {
            this._dotdot_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._dotdot_ = node;
    }

    public PExpression getEnd()
    {
        return this._end_;
    }

    public void setEnd(PExpression node)
    {
        if(this._end_ != null)
        {
            this._end_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._end_ = node;
    }

    public TRBracket getRBracket()
    {
        return this._rBracket_;
    }

    public void setRBracket(TRBracket node)
    {
        if(this._rBracket_ != null)
        {
            this._rBracket_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._rBracket_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._lBracket_)
            + toString(this._begin_)
            + toString(this._dotdot_)
            + toString(this._end_)
            + toString(this._rBracket_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._lBracket_ == child)
        {
            this._lBracket_ = null;
            return;
        }

        if(this._begin_ == child)
        {
            this._begin_ = null;
            return;
        }

        if(this._dotdot_ == child)
        {
            this._dotdot_ = null;
            return;
        }

        if(this._end_ == child)
        {
            this._end_ = null;
            return;
        }

        if(this._rBracket_ == child)
        {
            this._rBracket_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._lBracket_ == oldChild)
        {
            setLBracket((TLBracket) newChild);
            return;
        }

        if(this._begin_ == oldChild)
        {
            setBegin((PExpression) newChild);
            return;
        }

        if(this._dotdot_ == oldChild)
        {
            setDotdot((TDotdot) newChild);
            return;
        }

        if(this._end_ == oldChild)
        {
            setEnd((PExpression) newChild);
            return;
        }

        if(this._rBracket_ == oldChild)
        {
            setRBracket((TRBracket) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
