/*******************************************************************************
 * Copyright (c) 2006, 2007 Pfizer, Inc.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *   Jacob Brauer (WebReach, Inc.) - initial implementation
 *******************************************************************************/


package org.gello.runtime;

/**
 * The interface for "filter expression" classes generated by the compiler
 * to implement calls to collection operators such as "exists" and "select"
 * @author Erik Horstkotte
 */
public interface GelloFilter<T> {
    
    public GelloBoolean matches(T _instance);
}
