/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.gello.grammar.node;

import org.gello.grammar.analysis.*;

@SuppressWarnings("nls")
public final class AListJoinCollectionList extends PJoinCollectionList
{
    private PJoinCollectionList _joinCollectionList_;
    private TComma _comma_;
    private PJoinCollection _joinCollection_;

    public AListJoinCollectionList()
    {
        // Constructor
    }

    public AListJoinCollectionList(
        @SuppressWarnings("hiding") PJoinCollectionList _joinCollectionList_,
        @SuppressWarnings("hiding") TComma _comma_,
        @SuppressWarnings("hiding") PJoinCollection _joinCollection_)
    {
        // Constructor
        setJoinCollectionList(_joinCollectionList_);

        setComma(_comma_);

        setJoinCollection(_joinCollection_);

    }

    @Override
    public Object clone()
    {
        return new AListJoinCollectionList(
            cloneNode(this._joinCollectionList_),
            cloneNode(this._comma_),
            cloneNode(this._joinCollection_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAListJoinCollectionList(this);
    }

    public PJoinCollectionList getJoinCollectionList()
    {
        return this._joinCollectionList_;
    }

    public void setJoinCollectionList(PJoinCollectionList node)
    {
        if(this._joinCollectionList_ != null)
        {
            this._joinCollectionList_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._joinCollectionList_ = node;
    }

    public TComma getComma()
    {
        return this._comma_;
    }

    public void setComma(TComma node)
    {
        if(this._comma_ != null)
        {
            this._comma_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comma_ = node;
    }

    public PJoinCollection getJoinCollection()
    {
        return this._joinCollection_;
    }

    public void setJoinCollection(PJoinCollection node)
    {
        if(this._joinCollection_ != null)
        {
            this._joinCollection_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._joinCollection_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._joinCollectionList_)
            + toString(this._comma_)
            + toString(this._joinCollection_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._joinCollectionList_ == child)
        {
            this._joinCollectionList_ = null;
            return;
        }

        if(this._comma_ == child)
        {
            this._comma_ = null;
            return;
        }

        if(this._joinCollection_ == child)
        {
            this._joinCollection_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._joinCollectionList_ == oldChild)
        {
            setJoinCollectionList((PJoinCollectionList) newChild);
            return;
        }

        if(this._comma_ == oldChild)
        {
            setComma((TComma) newChild);
            return;
        }

        if(this._joinCollection_ == oldChild)
        {
            setJoinCollection((PJoinCollection) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
