/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.gello.grammar.node;

import org.gello.grammar.analysis.*;

@SuppressWarnings("nls")
public final class TEndcontext extends Token
{
    public TEndcontext()
    {
        super.setText("endContext");
    }

    public TEndcontext(int line, int pos)
    {
        super.setText("endContext");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TEndcontext(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTEndcontext(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TEndcontext text.");
    }
}
